version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=posgres_password
  redis:
    image: "redis:latest"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Inside the container, don't override this directory
      - ./server:/app
    environment:
      - REDIS_HOST=redis # use the service name
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # use the service name
      - PGDATABASE=postgres
      - PGPASSWORD=posgres_password
      - PGPORT=5432
